// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJWPakxqfvyoLGT_07yUq8IB2rD-eokE',
    appId: '1:588344277795:web:5c3138b76130dc73306a96',
    messagingSenderId: '588344277795',
    projectId: 'noted-a2eb9',
    authDomain: 'noted-a2eb9.firebaseapp.com',
    storageBucket: 'noted-a2eb9.appspot.com',
    measurementId: 'G-4D9K9T3QC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1EHQjKZBV2sYAZJ_kPJfr7duYb-za2OM',
    appId: '1:588344277795:android:d1fe06307125afc4306a96',
    messagingSenderId: '588344277795',
    projectId: 'noted-a2eb9',
    storageBucket: 'noted-a2eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxOSy-nvu9EpfnEB8r9l5ZmOXfIF3XDQ',
    appId: '1:588344277795:ios:753e1eba2965d1dd306a96',
    messagingSenderId: '588344277795',
    projectId: 'noted-a2eb9',
    storageBucket: 'noted-a2eb9.appspot.com',
    iosClientId: '588344277795-m1gmmro47iv9ihscha2kqg75p31fgurf.apps.googleusercontent.com',
    iosBundleId: 'com.example.Noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxOSy-nvu9EpfnEB8r9l5ZmOXfIF3XDQ',
    appId: '1:588344277795:ios:753e1eba2965d1dd306a96',
    messagingSenderId: '588344277795',
    projectId: 'noted-a2eb9',
    storageBucket: 'noted-a2eb9.appspot.com',
    iosClientId: '588344277795-m1gmmro47iv9ihscha2kqg75p31fgurf.apps.googleusercontent.com',
    iosBundleId: 'com.example.Noted',
  );
}
